### ISSUE TITLE
List is not supported

### ISSUE THREAD

**Issue by justinchuby** [justinchuby/torch-onnx#182]
```python

import onnx
import torch
import torch_onnx

class MHAWrapper(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.mha1 = torch.nn.MultiheadAttention(512, 8, batch_first=False)
    def forward(self, x, mask):
        return self.mha1(x, x, x, attn_mask=mask, need_weights=False)[0]

mha = MHAWrapper()
x = torch.rand(size=(62, 1, 512))
mask = torch.randint(0, 2, size=(62, 62), dtype=bool)

program = torch_onnx.export_compat(
    mha,
    (x, mask),
    "mha.onnx",
    verbose=True,
    input_names=["x", "mask"],
    output_names=["out"],
    dynamic_shapes=[
        {0: torch.export.Dim("num_elem")},
        {0: torch.export.Dim("num_elem"), 1: torch.export.Dim("num_elem")},
    ],
    dynamo=True,
    report=True
)

torch_onnx.testing.assert_onnx_program(program)
```

```python

import onnx
import torch
import torch_onnx

class MHAWrapper(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.mha1 = torch.nn.MultiheadAttention(512, 8, batch_first=False)
    def forward(self, x, mask):
        return self.mha1(x, x, x, attn_mask=mask, need_weights=False)[0]

mha = MHAWrapper()
x = torch.rand(size=(62, 1, 512))
mask = torch.randint(0, 2, size=(62, 62), dtype=bool)

program = torch_onnx.export_compat(
    mha,
    (x, mask),
    "mha.onnx",
    verbose=True,
    input_names=["x", "mask"],
    output_names=["out"],
    dynamic_axes={
        "x": {0: "num_elem"},
        "mask": {0: "num_elem", 1: "num_elem"},
    },
    dynamo=True
)

torch_onnx.testing.assert_onnx_program(program)
```

```pytb
[torch.onnx] Obtain model graph for `MHAWrapper([...]` with `torch.export.export`...
[torch.onnx] Obtain model graph for `MHAWrapper([...]` with `torch.export.export`... ✅
[torch.onnx] Translate the graph into ONNX...
[torch.onnx] Translate the graph into ONNX... ❌
Traceback (most recent call last):
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_building.py", line 367, in _call_op
    converted_named_inputs = _process_python_constants_and_sequences(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_building.py", line 275, in _process_python_constants_and_sequences
    raise TypeError(
TypeError: Constant input '[SymbolicTensor('sym_size_int_3', type=Tensor(INT64), shape=[], producer=node_Shape_0, index=0), 512]' of type '<class 'list'>' is not supported

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_building.py", line 422, in eval
    outputs = self._call_op(op_signature, named_inputs, named_attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_building.py", line 371, in _call_op
    raise errors.GraphConstructionError(
torch_onnx.errors.GraphConstructionError: Error processing Python constants for operator '::Cast'. named_inputs={'input': [SymbolicTensor('sym_size_int_3', type=Tensor(INT64), shape=[], producer=node_Shape_0, index=0), 512]}, named_attrs={'to': 7}, opset=, op_signature=''::Cast(input: T1, to: INT = None) -> (T2) where T1=BOOL | FLOAT | INT32 | FLOAT16 | UINT16 | UINT8 | UINT32 | DOUBLE | INT64 | INT16 | UINT64 | STRING | INT8 | BFLOAT16, T2=BOOL | FLOAT | INT32 | FLOAT16 | UINT16 | UINT8 | UINT32 | DOUBLE | INT64 | INT16 | UINT64 | STRING | INT8 | BFLOAT16.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 452, in _handle_call_function_node_with_lowering
    outputs = onnx_function(*onnx_args, **onnx_kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justinc/Documents/GitHub/torch-onnx/venv/lib/python3.11/site-packages/onnxscript/values.py", line 583, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justinc/Documents/GitHub/torch-onnx/venv/lib/python3.11/site-packages/onnxscript/function_libs/torch_lib/ops/core.py", line 8912, in aten_view
    size = op.Cast(size, to=INT64.dtype)  # Reshape only support INT64 as second input
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justinc/Documents/GitHub/torch-onnx/venv/lib/python3.11/site-packages/onnxscript/onnx_opset/_impl/opset13.py", line 291, in Cast
    return op(*self._prepare_inputs(schema, input), to=to)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justinc/Documents/GitHub/torch-onnx/venv/lib/python3.11/site-packages/onnxscript/values.py", line 301, in __call__
    return evaluator.default().eval(schema, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_building.py", line 427, in eval
    raise errors.GraphConstructionError(
torch_onnx.errors.GraphConstructionError: Error calling operator 'Cast' with args ([SymbolicTensor('sym_size_int_3', type=Tensor(INT64), shape=[], producer=node_Shape_0, index=0), 512],) and kwargs {'to': 7}.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 536, in _add_nodes
    _handle_call_function_node_with_lowering(
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 454, in _handle_call_function_node_with_lowering
    raise errors.GraphConstructionError(
torch_onnx.errors.GraphConstructionError: Error when calling function 'TracedOnnxFunction(<function aten_view at 0x3084fcf40>)' with args '[SymbolicTensor('x', type=Tensor(FLOAT), shape=[s0,1,512], producer=None, index=None), [SymbolicTensor('sym_size_int_3', type=Tensor(INT64), shape=[], producer=node_Shape_0, index=0), 512]]' and kwargs '{}'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 1117, in export
    onnx_program = _exported_program_to_onnx_program(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 774, in _exported_program_to_onnx_program
    values = _add_nodes(exported_program, model, lower=lower, registry=registry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 548, in _add_nodes
    raise errors.OnnxConversionError(
torch_onnx.errors.OnnxConversionError: Error when translating node %view : [num_users=1] = call_function[target=torch.ops.aten.view.default](args = (%x, [%sym_size_int_3, 512]), kwargs = {}). See the stack trace for more information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/justinc/Documents/GitHub/torch-onnx/test3.py", line 17, in <module>
    program = torch_onnx.export_compat(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_patch.py", line 165, in _torch_onnx_export
    onnx_program = _core.export(
                   ^^^^^^^^^^^^^
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 1161, in export
    raise errors.OnnxConversionError(
torch_onnx.errors.OnnxConversionError: Failed to convert the exported program to an ONNX model. This is step 2/2 of exporting the model to ONNX. Next steps:
- If there is a missing ONNX function, implement it and register it to the registry.
- If there is an internal error during ONNX conversion, debug the error and summit a PR to PyTorch.
- Save the ExportedProgram as a pt2 file and create an error report with `export(..., report=True)`. Create an issue in the PyTorch GitHub repository against the *onnx* component. Attach the pt2 model and the error report.

## Exception summary

<class 'TypeError'>: Constant input '[SymbolicTensor('sym_size_int_3', type=Tensor(INT64), shape=[], producer=node_Shape_0, index=0), 512]' of type '<class 'list'>' is not supported
⬆️
<class 'torch_onnx.errors.GraphConstructionError'>: Error processing Python constants for operator '::Cast'. named_inputs={'input': [SymbolicTensor('sym_size_int_3', type=Tensor(INT64), shape=[], producer=node_Shape_0, index=0), 512]}, named_attrs={'to': 7}, opset=, op_signature=''::Cast(input: T1, to: INT = None) -> (T2) where T1=BOOL | FLOAT | INT32 | FLOAT16 | UINT16 | UINT8 | UINT32 | DOUBLE | INT64 | INT16 | UINT64 | STRING | INT8 | BFLOAT16, T2=BOOL | FLOAT | INT32 | FLOAT16 | UINT16 | UINT8 | UINT32 | DOUBLE | INT64 | INT16 | UINT64 | STRING | INT8 | BFLOAT16.
⬆️
<class 'torch_onnx.errors.GraphConstructionError'>: Error calling operator 'Cast' with args ([SymbolicTensor('sym_size_int_3', type=Tensor(INT64), shape=[], producer=node_Shape_0, index=0), 512],) and kwargs {'to': 7}.
⬆️
<class 'torch_onnx.errors.GraphConstructionError'>: Error when calling function 'TracedOnnxFunction(<function aten_view at 0x3084fcf40>)' with args '[SymbolicTensor('x', type=Tensor(FLOAT), shape=[s0,1,512], producer=None, index=None), [SymbolicTensor('sym_size_int_3', type=Tensor(INT64), shape=[], producer=node_Shape_0, index=0), 512]]' and kwargs '{}'
⬆️
<class 'torch_onnx.errors.OnnxConversionError'>: Error when translating node %view : [num_users=1] = call_function[target=torch.ops.aten.view.default](args = (%x, [%sym_size_int_3, 512]), kwargs = {}). See the stack trace for more information.

(Refer to the full stack trace above for more information.)
```

**Comment by justinchuby** [comment]
https://github.com/pytorch/pytorch/issues/120075
