### ISSUE TITLE
'tuple' object has no attribute 'metadata_props'

### ISSUE THREAD

**Issue by justinchuby** [justinchuby/torch-onnx#35]
# PyTorch ONNX Conversion Error Report

```
✅ Obtain model graph with `torch.export.export`
❌ Translate the graph into ONNX
⚪ Run `onnx.checker` on the ONNX model
⚪ Execute the model with ONNX Runtime
⚪ Validate model output accuracy
```

Error message:

```pytb
Traceback (most recent call last):
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_patch.py", line 222, in _torch_onnx_export
    ir_model = torch_onnx.exported_program_to_ir(program)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 682, in exported_program_to_ir
    value.metadata_props["pkg.torch.export.graph_signature.OutputSpec.kind"] = (
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'metadata_props'
```

Exported program:

```python
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, arg0_1: "f32[4, 3]", arg1_1: "f32[4, 3]", arg2_1: "i64[4]"):
            # File: /Users/justinc/Documents/GitHub/torch-onnx/tests/torch_tests/torch_onnx_test.py:9519 in forward, code: return self.emb(input), self.emb2(input)
            embedding: "f32[4, 3]" = torch.ops.aten.embedding.default(arg0_1, arg2_1, 1);  arg0_1 = None
            embedding_1: "f32[4, 3]" = torch.ops.aten.embedding.default(arg1_1, arg2_1, 1);  arg1_1 = arg2_1 = None
            return (embedding, embedding_1)
            
Graph signature: ExportGraphSignature(input_specs=[InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='arg0_1'), target='emb.weight', persistent=None), InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='arg1_1'), target='emb2.weight', persistent=None), InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='arg2_1'), target=None, persistent=None)], output_specs=[OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='embedding'), target=None), OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='embedding_1'), target=None)])
Range constraints: {}
```

## Analysis

PyTorch ONNX Conversion Analysis

## Model Information

The model has 24 parameters and 0 buffers (non-trainable parameters).
Number of parameters per dtype:
```python
defaultdict(<class 'int'>, {torch.float32: 24})
```
Number of buffers per dtype:
```python
defaultdict(<class 'int'>, {})
```

Inputs:
- `arg2_1`: `TensorMetadata(shape=torch.Size([4]), dtype=torch.int64, requires_grad=False, stride=(1,), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`

Outputs:
- `embedding`: `TensorMetadata(shape=torch.Size([4, 3]), dtype=torch.float32, requires_grad=False, stride=(3, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`
- `embedding_1`: `TensorMetadata(shape=torch.Size([4, 3]), dtype=torch.float32, requires_grad=False, stride=(3, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`

The FX graph has 6 nodes in total. Number of FX nodes per op:
- `placeholder`: 3
- `call_function`: 2
- `output`: 1

Of the call_function nodes, the counts of operators used are:

- `aten.embedding.default`: 2

## ONNX Conversion Information

All operators in the model have registered ONNX decompositions.

**Comment by justinchuby** [comment]
# PyTorch ONNX Conversion Error Report

```
✅ Obtain model graph with `torch.export.export`
❌ Translate the graph into ONNX
⚪ Run `onnx.checker` on the ONNX model
⚪ Execute the model with ONNX Runtime
⚪ Validate model output accuracy
```

Error message:

```pytb
Traceback (most recent call last):
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_patch.py", line 222, in _torch_onnx_export
    ir_model = torch_onnx.exported_program_to_ir(program)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 682, in exported_program_to_ir
    value.metadata_props["pkg.torch.export.graph_signature.OutputSpec.kind"] = (
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'metadata_props'
```

Exported program:

```python
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, arg0_1: "i64[4]", arg1_1: "f32[10, 3]"):
            # File: /Users/justinc/Documents/GitHub/torch-onnx/tests/torch_tests/torch_onnx_test.py:9485 in forward, code: return torch.nn.functional.embedding(input, emb, padding_idx=1)
            embedding: "f32[4, 3]" = torch.ops.aten.embedding.default(arg1_1, arg0_1, 1);  arg1_1 = arg0_1 = None
            return (embedding,)
            
Graph signature: ExportGraphSignature(input_specs=[InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='arg0_1'), target=None, persistent=None), InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='arg1_1'), target=None, persistent=None)], output_specs=[OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='embedding'), target=None)])
Range constraints: {}
```

## Analysis

PyTorch ONNX Conversion Analysis

## Model Information

The model has 0 parameters and 0 buffers (non-trainable parameters).
Number of parameters per dtype:
```python
defaultdict(<class 'int'>, {})
```
Number of buffers per dtype:
```python
defaultdict(<class 'int'>, {})
```

Inputs:
- `arg0_1`: `TensorMetadata(shape=torch.Size([4]), dtype=torch.int64, requires_grad=False, stride=(1,), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`
- `arg1_1`: `TensorMetadata(shape=torch.Size([10, 3]), dtype=torch.float32, requires_grad=False, stride=(3, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`

Outputs:
- `embedding`: `TensorMetadata(shape=torch.Size([4, 3]), dtype=torch.float32, requires_grad=False, stride=(3, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`

The FX graph has 4 nodes in total. Number of FX nodes per op:
- `placeholder`: 2
- `call_function`: 1
- `output`: 1


Of the call_function nodes, the counts of operators used are:

- `aten.embedding.default`: 1

## ONNX Conversion Information

All operators in the model have registered ONNX decompositions.

**Comment by justinchuby** [comment]
This is due to an incorrect signature in aten.embedding in torchlib
