### ISSUE TITLE
bitwise_and cannot be matched

### ISSUE THREAD

**Issue by justinchuby** [justinchuby/torch-onnx#36]
# PyTorch ONNX Conversion Error Report

```
✅ Obtain model graph with `torch.export.export`
❌ Translate the graph into ONNX
⚪ Run `onnx.checker` on the ONNX model
⚪ Execute the model with ONNX Runtime
⚪ Validate model output accuracy
```

Error message:

```pytb
Traceback (most recent call last):
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 490, in _add_nodes
    _handle_call_function_node_with_lowering(
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 372, in _handle_call_function_node_with_lowering
    raise RuntimeError(
RuntimeError: No ONNX function found for <OpOverload(op='aten.bitwise_and', overload='Tensor')>. Failure message: All overloads did not match the node `%bitwise_and : [num_users=1] = call_function[target=torch.ops.aten.bitwise_and.Tensor](args = (%arg0_1, %scalar_tensor_default), kwargs = {})`.
- Failed to match overload `OnnxFunction(<function aten_bitwise_and at 0x14f19fa60>)`: Parameter type not compatible with argument: param=`Parameter(name='self', type_constraint=TypeConstraintParam(name='TInt', allowed_types={Tensor(INT32), Tensor(INT64), Tensor(INT8), Tensor(INT16)}, description=''), required=True, variadic=False, default=_EMPTY_DEFAULT)`, assigned_types=`{}`, arg=`UINT8`
- Failed to match overload `OnnxFunction(<function aten_logical_and at 0x14f4fdda0>)`: Parameter type not compatible with argument: param=`Parameter(name='self', type_constraint=TypeConstraintParam(name='T_self', allowed_types={Tensor(BOOL)}, description=''), required=True, variadic=False, default=_EMPTY_DEFAULT)`, assigned_types=`{}`, arg=`UINT8`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_patch.py", line 222, in _torch_onnx_export
    ir_model = torch_onnx.exported_program_to_ir(program)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 626, in exported_program_to_ir
    values = _add_nodes(exported_program, model, lower=lower, registry=registry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 501, in _add_nodes
    raise RuntimeError(
RuntimeError: Error when translating node %bitwise_and : [num_users=1] = call_function[target=torch.ops.aten.bitwise_and.Tensor](args = (%arg0_1, %scalar_tensor_default), kwargs = {}). See the stack trace for more information.
```

Exported program:

```python
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, _lifted_tensor_constant0: "i32[2]", arg0_1: "u8[3, 4, 2]", arg1_1: "i8[3, 4, 2]"):
            # File: /Users/justinc/Documents/GitHub/torch-onnx/tests/torch_tests/torch_onnx_test.py:3538 in forward, code: input & 20,
            scalar_tensor_default: "u8[]" = torch.ops.aten.scalar_tensor.default(20, dtype = torch.uint8)
            bitwise_and: "u8[3, 4, 2]" = torch.ops.aten.bitwise_and.Tensor(arg0_1, scalar_tensor_default);  scalar_tensor_default = None
            
            # File: /Users/justinc/Documents/GitHub/torch-onnx/tests/torch_tests/torch_onnx_test.py:3539 in forward, code: torch.bitwise_and(input, other),
            convert_element_type_default: "i16[3, 4, 2]" = torch.ops.prims.convert_element_type.default(arg0_1, dtype = torch.int16);  arg0_1 = None
            convert_element_type_default_1: "i16[3, 4, 2]" = torch.ops.prims.convert_element_type.default(arg1_1, dtype = torch.int16)
            bitwise_and_1: "i16[3, 4, 2]" = torch.ops.aten.bitwise_and.Tensor(convert_element_type_default, convert_element_type_default_1);  convert_element_type_default = convert_element_type_default_1 = None
            
            # File: /Users/justinc/Documents/GitHub/torch-onnx/tests/torch_tests/torch_onnx_test.py:3540 in forward, code: other & torch.tensor([1, 2], dtype=torch.int32),
            lift_fresh_copy: "i32[2]" = torch.ops.aten.lift_fresh_copy.default(_lifted_tensor_constant0);  _lifted_tensor_constant0 = None
            convert_element_type_default_2: "i32[3, 4, 2]" = torch.ops.prims.convert_element_type.default(arg1_1, dtype = torch.int32);  arg1_1 = None
            bitwise_and_2: "i32[3, 4, 2]" = torch.ops.aten.bitwise_and.Tensor(convert_element_type_default_2, lift_fresh_copy);  convert_element_type_default_2 = lift_fresh_copy = None
            return (bitwise_and, bitwise_and_1, bitwise_and_2)
            
Graph signature: ExportGraphSignature(input_specs=[InputSpec(kind=<InputKind.CONSTANT_TENSOR: 4>, arg=TensorArgument(name='_lifted_tensor_constant0'), target='_lifted_tensor_constant0', persistent=None), InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='arg0_1'), target=None, persistent=None), InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='arg1_1'), target=None, persistent=None)], output_specs=[OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='bitwise_and'), target=None), OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='bitwise_and_1'), target=None), OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='bitwise_and_2'), target=None)])
Range constraints: {}
```

## Analysis

PyTorch ONNX Conversion Analysis

## Model Information

The model has 0 parameters and 0 buffers (non-trainable parameters).
Number of parameters per dtype:
```python
defaultdict(<class 'int'>, {})
```
Number of buffers per dtype:
```python
defaultdict(<class 'int'>, {})
```

Inputs:
- `arg0_1`: `TensorMetadata(shape=torch.Size([3, 4, 2]), dtype=torch.uint8, requires_grad=False, stride=(8, 2, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`
- `arg1_1`: `TensorMetadata(shape=torch.Size([3, 4, 2]), dtype=torch.int8, requires_grad=False, stride=(8, 2, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`

Outputs:
- `bitwise_and`: `TensorMetadata(shape=torch.Size([3, 4, 2]), dtype=torch.uint8, requires_grad=False, stride=(8, 2, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`
- `bitwise_and_1`: `TensorMetadata(shape=torch.Size([3, 4, 2]), dtype=torch.int16, requires_grad=False, stride=(8, 2, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`
- `bitwise_and_2`: `TensorMetadata(shape=torch.Size([3, 4, 2]), dtype=torch.int32, requires_grad=False, stride=(8, 2, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`

The FX graph has 12 nodes in total. Number of FX nodes per op:
- `placeholder`: 3
- `call_function`: 8
- `output`: 1

Of the call_function nodes, the counts of operators used are:

- `aten.bitwise_and.Tensor`: 3
- `prims.convert_element_type.default`: 3
- `aten.scalar_tensor.default`: 1
- `aten.lift_fresh_copy.default`: 1

## ONNX Conversion Information

The model contains operators the dispatcher could not find registered ONNX decompositions for. This may be due to missing implementations, decompositions not registered correctly, or a bug in the dispatcher.

Errors grouped by operator:

- `aten.bitwise_and.Tensor`:     All overloads did not match the node `%bitwise_and : [num_users=1] = call_function[target=torch.ops.aten.bitwise_and.Tensor](args = (%arg0_1, %scalar_tensor_default), kwargs = {})`.
    - Failed to match overload `OnnxFunction(<function aten_bitwise_and at 0x14f19fa60>)`: Parameter type not compatible with argument: param=`Parameter(name='self', type_constraint=TypeConstraintParam(name='TInt', allowed_types={Tensor(INT32), Tensor(INT64), Tensor(INT8), Tensor(INT16)}, description=''), required=True, variadic=False, default=_EMPTY_DEFAULT)`, assigned_types=`{}`, arg=`UINT8`
    - Failed to match overload `OnnxFunction(<function aten_logical_and at 0x14f4fdda0>)`: Parameter type not compatible with argument: param=`Parameter(name='self', type_constraint=TypeConstraintParam(name='T_self', allowed_types={Tensor(BOOL)}, description=''), required=True, variadic=False, default=_EMPTY_DEFAULT)`, assigned_types=`{}`, arg=`UINT8`. Example node: `%bitwise_and : [num_users=1] = call_function[target=torch.ops.aten.bitwise_and.Tensor](args = (%arg0_1, %scalar_tensor_default), kwargs = {})`. All nodes: `[bitwise_and]`

**Comment by justinchuby** [comment]
uint8 is not supported
