### ISSUE TITLE
'SymBool' object is not iterable

### ISSUE THREAD

**Issue by justinchuby** [justinchuby/torch-onnx#42]
# PyTorch ONNX Conversion Error Report

```
✅ Obtain model graph with `torch.export.export`
❌ Translate the graph into ONNX
⚪ Run `onnx.checker` on the ONNX model
⚪ Execute the model with ONNX Runtime
⚪ Validate model output accuracy
```

Error message:

```pytb
Traceback (most recent call last):

  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 497, in _add_nodes
    _handle_call_function_node_with_lowering(

  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 375, in _handle_call_function_node_with_lowering
    onnx_function, message = _dispatching.dispatch(node, registry)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 323, in dispatch
    overload, message = get_matching_overload(
                        ^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 208, in get_matching_overload
    named_args = _get_named_fx_node_args(node)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 186, in _get_named_fx_node_args
    torch_schema: torch.FunctionSchema = node.target._schema
                                         ^^^^^^^^^^^^^^^^^^^

AttributeError: 'builtin_function_or_method' object has no attribute '_schema'


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_patch.py", line 196, in _torch_onnx_export
    ir_model = torch_onnx.exported_program_to_ir(program)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 633, in exported_program_to_ir
    values = _add_nodes(exported_program, model, lower=lower, registry=registry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 508, in _add_nodes
    raise errors.OnnxConversionError(

torch_onnx.errors.OnnxConversionError: Error when translating node %ge : [num_users=1] = call_function[target=operator.ge](args = (%_local_scalar_dense_1, -9223372036854775808), kwargs = {}). See the stack trace for more information.
```

Exported program:

```python
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, arg0_1: "f32[10, 3, 5]", arg1_1: "f32[10, 3, 4]", arg2_1: "f32[10, 4, 5]", arg3_1: "i64[]", arg4_1: "f32[]"):
            # File: /Users/justinc/Documents/GitHub/torch-onnx/tests/torch_tests/torch_onnx_test.py:7386 in forward, code: return torch.baddbmm(input, batch1, batch2, alpha=alpha, beta=beta)
            _local_scalar_dense: "Sym(f4)" = torch.ops.aten._local_scalar_dense.default(arg4_1);  arg4_1 = None
            _local_scalar_dense_1: "Sym(u4)" = torch.ops.aten._local_scalar_dense.default(arg3_1);  arg3_1 = None
            
            # File: /Users/justinc/Documents/GitHub/torch-onnx/venv/lib/python3.11/site-packages/torch/_export/pass_base.py:54 in _create_dummy_node_metadata, code: return NodeMetadata({"stack_trace": "".join(traceback.format_stack(limit=1))})
            ge: "Sym(u4 >= -9223372036854775808)" = _local_scalar_dense_1 >= -9223372036854775808
            scalar_tensor: "f32[]" = torch.ops.aten.scalar_tensor.default(ge);  ge = None
            _assert_async = torch.ops.aten._assert_async.msg(scalar_tensor, '_local_scalar_dense_1 is outside of inline constraint [-9223372036854775808, 9223372036854775807].');  scalar_tensor = None
            le: "Sym(u4 <= 9223372036854775807)" = _local_scalar_dense_1 <= 9223372036854775807
            scalar_tensor_1: "f32[]" = torch.ops.aten.scalar_tensor.default(le);  le = None
            _assert_async_1 = torch.ops.aten._assert_async.msg(scalar_tensor_1, '_local_scalar_dense_1 is outside of inline constraint [-9223372036854775808, 9223372036854775807].');  scalar_tensor_1 = None
            
            # File: /Users/justinc/Documents/GitHub/torch-onnx/tests/torch_tests/torch_onnx_test.py:7386 in forward, code: return torch.baddbmm(input, batch1, batch2, alpha=alpha, beta=beta)
            baddbmm: "f32[10, 3, 5]" = torch.ops.aten.baddbmm.default(arg0_1, arg1_1, arg2_1, beta = _local_scalar_dense, alpha = _local_scalar_dense_1);  arg0_1 = arg1_1 = arg2_1 = _local_scalar_dense = _local_scalar_dense_1 = None
            return (baddbmm,)
            
Graph signature: ExportGraphSignature(input_specs=[InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='arg0_1'), target=None, persistent=None), InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='arg1_1'), target=None, persistent=None), InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='arg2_1'), target=None, persistent=None), InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='arg3_1'), target=None, persistent=None), InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='arg4_1'), target=None, persistent=None)], output_specs=[OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='baddbmm'), target=None)])
Range constraints: {f0: ValueRanges(lower=-oo, upper=oo, is_bool=False), u0: ValueRanges(lower=-9223372036854775808, upper=9223372036854775807, is_bool=False), f1: ValueRanges(lower=-oo, upper=oo, is_bool=False), u1: ValueRanges(lower=-9223372036854775808, upper=9223372036854775807, is_bool=False), f2: ValueRanges(lower=-oo, upper=oo, is_bool=False), u2: ValueRanges(lower=-9223372036854775808, upper=9223372036854775807, is_bool=False), f3: ValueRanges(lower=-oo, upper=oo, is_bool=False), u3: ValueRanges(lower=-9223372036854775808, upper=9223372036854775807, is_bool=False), f4: ValueRanges(lower=-oo, upper=oo, is_bool=False), u4: ValueRanges(lower=-9223372036854775808, upper=9223372036854775807, is_bool=False)}
```

## Analysis

PyTorch ONNX Conversion Analysis

## Model Information

The model has 0 parameters and 0 buffers (non-trainable parameters).
Number of parameters per dtype:
```python
defaultdict(<class 'int'>, {})
```
Number of buffers per dtype:
```python
defaultdict(<class 'int'>, {})
```

Inputs:
- `arg0_1`: `None`
- `arg1_1`: `None`
- `arg2_1`: `None`
- `arg3_1`: `None`
- `arg4_1`: `None`

Outputs:
- `baddbmm`: `None`

The FX graph has 15 nodes in total. Number of FX nodes per op:
- `placeholder`: 5
- `call_function`: 9
- `output`: 1

Of the call_function nodes, the counts of operators used are:

- `aten._local_scalar_dense.default`: 2
- `aten.scalar_tensor.default`: 2
- `aten._assert_async.msg`: 2
- `<built-in function ge>`: 1
- `<built-in function le>`: 1
- `aten.baddbmm.default`: 1

## ONNX Conversion Information

The model contains operators the dispatcher could not find registered ONNX decompositions for. This may be due to missing implementations, decompositions not registered correctly, or a bug in the dispatcher.

Errors grouped by operator:

- `aten.scalar_tensor.default`:     Critical Error in dispatcher:
    ```pytb
    Traceback (most recent call last):

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 497, in _add_nodes
        _handle_call_function_node_with_lowering(

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 375, in _handle_call_function_node_with_lowering
        onnx_function, message = _dispatching.dispatch(node, registry)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 323, in dispatch
        overload, message = get_matching_overload(
                            ^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 208, in get_matching_overload
        named_args = _get_named_fx_node_args(node)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 186, in _get_named_fx_node_args
        torch_schema: torch.FunctionSchema = node.target._schema
                                             ^^^^^^^^^^^^^^^^^^^

    AttributeError: 'builtin_function_or_method' object has no attribute '_schema'


    The above exception was the direct cause of the following exception:


    Traceback (most recent call last):

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_patch.py", line 196, in _torch_onnx_export
        ir_model = torch_onnx.exported_program_to_ir(program)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 633, in exported_program_to_ir
        values = _add_nodes(exported_program, model, lower=lower, registry=registry)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 508, in _add_nodes
        raise errors.OnnxConversionError(

    torch_onnx.errors.OnnxConversionError: Error when translating node %ge : [num_users=1] = call_function[target=operator.ge](args = (%_local_scalar_dense_1, -9223372036854775808), kwargs = {}). See the stack trace for more information.


    During handling of the above exception, another exception occurred:


    Traceback (most recent call last):

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_analysis.py", line 209, in analyze
        onnx_function, message = _dispatching.dispatch(node, registry)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 323, in dispatch
        overload, message = get_matching_overload(
                            ^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 254, in get_matching_overload
        arg = _get_type_from_tensor(meta_val)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 168, in _get_type_from_tensor
        first_tensor = next((item for item in tensor if item is not None), None)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    TypeError: 'SymBool' object is not iterable

    ```
    . Example node: `%scalar_tensor : [num_users=1] = call_function[target=torch.ops.aten.scalar_tensor.default](args = (%ge,), kwargs = {})`. All nodes: `[scalar_tensor, scalar_tensor_1]`
- `aten._assert_async.msg`:     No decompositions registered for the real-valued input. Example node: `%_assert_async : [num_users=0] = call_function[target=torch.ops.aten._assert_async.msg](args = (%scalar_tensor, _local_scalar_dense_1 is outside of inline constraint [-9223372036854775808, 9223372036854775807].), kwargs = {})`. All nodes: `[_assert_async, _assert_async_1]`
- `<built-in function le>`:     Critical Error in dispatcher:
    ```pytb
    Traceback (most recent call last):

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 497, in _add_nodes
        _handle_call_function_node_with_lowering(

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 375, in _handle_call_function_node_with_lowering
        onnx_function, message = _dispatching.dispatch(node, registry)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 323, in dispatch
        overload, message = get_matching_overload(
                            ^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 208, in get_matching_overload
        named_args = _get_named_fx_node_args(node)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 186, in _get_named_fx_node_args
        torch_schema: torch.FunctionSchema = node.target._schema
                                             ^^^^^^^^^^^^^^^^^^^

    AttributeError: 'builtin_function_or_method' object has no attribute '_schema'


    The above exception was the direct cause of the following exception:


    Traceback (most recent call last):

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_patch.py", line 196, in _torch_onnx_export
        ir_model = torch_onnx.exported_program_to_ir(program)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 633, in exported_program_to_ir
        values = _add_nodes(exported_program, model, lower=lower, registry=registry)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 508, in _add_nodes
        raise errors.OnnxConversionError(

    torch_onnx.errors.OnnxConversionError: Error when translating node %ge : [num_users=1] = call_function[target=operator.ge](args = (%_local_scalar_dense_1, -9223372036854775808), kwargs = {}). See the stack trace for more information.


    During handling of the above exception, another exception occurred:


    Traceback (most recent call last):

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_analysis.py", line 209, in analyze
        onnx_function, message = _dispatching.dispatch(node, registry)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 323, in dispatch
        overload, message = get_matching_overload(
                            ^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 208, in get_matching_overload
        named_args = _get_named_fx_node_args(node)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 186, in _get_named_fx_node_args
        torch_schema: torch.FunctionSchema = node.target._schema
                                             ^^^^^^^^^^^^^^^^^^^

    AttributeError: 'builtin_function_or_method' object has no attribute '_schema'

    ```
    . Example node: `%le : [num_users=1] = call_function[target=operator.le](args = (%_local_scalar_dense_1, 9223372036854775807), kwargs = {})`. All nodes: `[le]`
- `<built-in function ge>`:     Critical Error in dispatcher:
    ```pytb
    Traceback (most recent call last):

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 497, in _add_nodes
        _handle_call_function_node_with_lowering(

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 375, in _handle_call_function_node_with_lowering
        onnx_function, message = _dispatching.dispatch(node, registry)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 323, in dispatch
        overload, message = get_matching_overload(
                            ^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 208, in get_matching_overload
        named_args = _get_named_fx_node_args(node)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 186, in _get_named_fx_node_args
        torch_schema: torch.FunctionSchema = node.target._schema
                                             ^^^^^^^^^^^^^^^^^^^

    AttributeError: 'builtin_function_or_method' object has no attribute '_schema'


    The above exception was the direct cause of the following exception:


    Traceback (most recent call last):

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_patch.py", line 196, in _torch_onnx_export
        ir_model = torch_onnx.exported_program_to_ir(program)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 633, in exported_program_to_ir
        values = _add_nodes(exported_program, model, lower=lower, registry=registry)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 508, in _add_nodes
        raise errors.OnnxConversionError(

    torch_onnx.errors.OnnxConversionError: Error when translating node %ge : [num_users=1] = call_function[target=operator.ge](args = (%_local_scalar_dense_1, -9223372036854775808), kwargs = {}). See the stack trace for more information.


    During handling of the above exception, another exception occurred:


    Traceback (most recent call last):

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_analysis.py", line 209, in analyze
        onnx_function, message = _dispatching.dispatch(node, registry)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 323, in dispatch
        overload, message = get_matching_overload(
                            ^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 208, in get_matching_overload
        named_args = _get_named_fx_node_args(node)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_dispatching.py", line 186, in _get_named_fx_node_args
        torch_schema: torch.FunctionSchema = node.target._schema
                                             ^^^^^^^^^^^^^^^^^^^

    AttributeError: 'builtin_function_or_method' object has no attribute '_schema'

    ```
    . Example node: `%ge : [num_users=1] = call_function[target=operator.ge](args = (%_local_scalar_dense_1, -9223372036854775808), kwargs = {})`. All nodes: `[ge]`

**Comment by justinchuby** [comment]
https://github.com/justinchuby/torch-onnx/blob/786e0d93b1a2b526ecbc89f65fea4d315599f0bb/src/torch_onnx/_dispatching.py#L168-L178
