### ISSUE TITLE
Output 0 is out of bounds

### ISSUE THREAD

**Issue by justinchuby** [justinchuby/torch-onnx#63]
# PyTorch ONNX Conversion Error Report

```
✅ Obtain model graph with `torch.export.export`
✅ Translate the graph into ONNX
❌ Run `onnx.checker` on the ONNX model
⚪ Execute the model with ONNX Runtime
⚪ Validate model output accuracy
```

Error message:

```pytb
Traceback (most recent call last):

  File "/Users/justinc/Documents/GitHub/torch-onnx/src/torch_onnx/_core.py", line 911, in export
    onnx.checker.check_model(onnx_program.model_proto, full_check=True)

  File "/Users/justinc/Documents/GitHub/torch-onnx/venv/lib/python3.11/site-packages/onnx/checker.py", line 179, in check_model
    C.check_model(

onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:aten_zeros, node name: node_aten_zeros_1): Output 0 is out of bounds.
```

## Analysis

PyTorch ONNX Conversion Analysis

## Model Information

The model has 2176 parameters and 0 buffers (non-trainable parameters).
Number of parameters per dtype:
```python
defaultdict(<class 'int'>, {torch.float32: 2176})
```
Number of buffers per dtype:
```python
defaultdict(<class 'int'>, {})
```

Inputs:
- `arg4_1`: `TensorMetadata(shape=torch.Size([10, 16, 16]), dtype=torch.float32, requires_grad=False, stride=(256, 16, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`

Outputs:
- `cat`: `TensorMetadata(shape=torch.Size([10, 16, 16]), dtype=torch.float32, requires_grad=False, stride=(256, 16, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={})`
- `stack`: `TensorMetadata(shape=torch.Size([1, 1, 16, 16]), dtype=torch.float32, requires_grad=False, stride=(256, 256, 16, 1), memory_format=torch.channels_last, is_quantized=False, qparams={})`
- `stack_1`: `TensorMetadata(shape=torch.Size([1, 1, 16, 16]), dtype=torch.float32, requires_grad=False, stride=(256, 256, 16, 1), memory_format=torch.channels_last, is_quantized=False, qparams={})`

The FX graph has 224 nodes in total. Number of FX nodes per op:
- `placeholder`: 5
- `call_function`: 218
- `output`: 1

Of the call_function nodes, the counts of operators used are:

- `<built-in function getitem>`: 52
- `aten.sigmoid.default`: 30
- `aten.mul.Tensor`: 30
- `aten.view.default`: 22
- `aten.add.Tensor`: 20
- `aten.tanh.default`: 20
- `aten.t.default`: 11
- `aten.addmm.default`: 11
- `aten.split.Tensor`: 10
- `aten.unbind.int`: 3
- `aten.zeros.default`: 2
- `aten.unsqueeze.default`: 2
- `aten.squeeze.dim`: 2
- `aten.stack.default`: 2
- `aten.cat.default`: 1

## ONNX Conversion Information

All operators in the model have registered ONNX decompositions.

**Comment by justinchuby** [comment]
This is because the torchlib functions do not have return types annotated correctly.
